Bank/Bank/urls.py
# Code written by Plamen Kolev


from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = patterns('',

    url(r'^$','Bank.views.index', name='index'),
    # link the index page with the account view for now, 90% will change later
    url(r'^testhtml$','Bank.views.testHtml', name='testHtml'),
    # link the index page with the account view for now, 90% will change later
    url(r'^payment/', include('payment.urls')),
    # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    url(r'^info/', include('userprofile.urls')),
    # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    url(r'^generator/', include('generator.urls')),
    # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    url(r'^admin/', include(admin.site.urls)),
    # default django admin
    url(r'^notifications/', include('notification.urls')),
    # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    url(r'^help/', include('help.urls')),
    # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    #urlconf for the content_controller
    url(r'^profile/', include('content_controller.urls')), # this is a redirect to the url config inside the account app, look inside account.urls for the mapping
    url(r'^budget/', include('budget.urls')),
    # the login and logout use the default django contrib authentication system (for more details view the admin panel under auth, thats where it gets it's hooks)
    # it is customizable, for example here we pass the template where we have minimal code to just render the username and massword, name is used for indication for action="?" in forms that require login, aka form loopback
    url(r'^login/$', 'django.contrib.auth.views.login',  {'template_name': 'payment/login.html'}, name="my_login"),
    #  the next_page argument just sends you to the homepage after you log in, otherwise you get the default django login auth
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url('^change-password/', 'django.contrib.auth.views.password_change', name="change_password"),
    url(r'^password/changed$', 'django.contrib.auth.views.password_change', {'password_change_done': '/settings/users/password-changed'}),
    url(r'^user/password_change/done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),

     url(r'^api/', include('api.urls')), # this is a redirect to the url config inside the account app, look inside account.urls for the mapping

    (r'^tinymce/', include('tinymce.urls')), # for tiny mce (rich text field)
) #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns) # enables restful api functionality (wrapper)

Bank/api/urls.py
# Code written by Plamen Kolev

from django.conf.urls import include, url, patterns
from django.contrib import admin
import Bank,api,views
from rest_framework.authtoken import views as tokenview

urlpatterns = patterns('',

    url(r'^accounts/$', api.views.AccountList.as_view()),
    url(r'^accounts/(?P<pk>[0-9]+)/$', views.AccountDetail.as_view()),
    
    url(r'^userstories$', 'api.views.getUserStories', name='userStories'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.BankingPerson.as_view()),

    url(r'^safedial/token/(?P<number>[0-9]+)/(?P<username>\w+)$', views.GetSafedialKey.as_view()),


    url(r'^notifications/$', views.NotificationList.as_view()),
    url(r'^notifications/(?P<pk>[0-9]+)/$', views.NotificationDetail.as_view()),
    url(r'^markViewed/$', 'api.views.markNotificationsViewed', name='markNotificationsViewed'),
    
    url(r'^outgoing/$', views.OutgoingTransactionList.as_view()),
    url(r'^outgoing/(?P<pk>[0-9]+)/$', views.OutgoingTransactionDetail.as_view()),

    url(r'^incoming/$', views.IncomingTransactionList.as_view()),
    url(r'^incoming/(?P<pk>[0-9]+)/$', views.IncomingTransactionDetail.as_view()),

    url(r'^savedpay/$', views.SavedPayeeList.as_view(), name="savedpay"),
    url(r'^savedpay/(?P<pk>[0-9]+)/$', views.SavedPayeeDetail.as_view()),

    # AUTH
    url(r'^auth/$', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^token/$', tokenview.obtain_auth_token),

# api urls
)

Bank/payment/urls.py
# Code written by Plamen Kolev

from django.conf.urls import include, url, patterns

urlpatterns = patterns("payment",
    url(r'^send/$', 'views.sendMoney', name='sendMoney'),
    url(r'^statement/(?P<pk>\d+)$', 'views.statement', name='statement'),
    url(r'^account/rename/(?P<pk>\d+)$', 'views.change_account_name', name='change_account_name'),
    url(r'^save_to_payee$', 'views.save_to_payee', name='save_to_payee'),

    # api

)

Bank/payment/models.py
# Code written by Plamen Kolev

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from notification.models import Notification
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.dispatch.dispatcher import receiver
from django.contrib.auth.signals import user_logged_in
import random
import string
from rest_framework.authtoken.models import Token

# TODO make a sql table when a collision happens
# Validators (does the account number length and the sort code)
def validate_iban(value):
    validationDigit = 22 # set the value for custom account digits
    digitLength = len(str(value))#length of digits
    if digitLength != validationDigit:
        raise ValidationError("Iban number must be %d digit, %d given instead !" % (validationDigit, digitLength))

def validate_sort(value):
    validationDigit = 6 # set the value for custom account digits
    digitLength = len(str(value))
    if digitLength != validationDigit:
        raise ValidationError("Sort-code must be %d digit, %d given instead !" % (validationDigit, digitLength))

def validate_transaction_amount(value):
    if value <= 0:
        raise ValidationError("The field cannot be zero or negative !")
# End of validators

class SavedPayee(models.Model):
    name = models.CharField(max_length=100)
    iban = models.CharField(max_length=22, validators = [validate_iban])
    sortCode = models.CharField(max_length=6, validators = [validate_sort])
    owner = models.ForeignKey(User)

class UserLogin(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False, default=timezone.now())

class BankingPerson(models.Model):

    user = models.OneToOneField(User, primary_key=True)
    address = models.CharField(max_length=600)
    phone = models.CharField(max_length=12)
    email= models.CharField(max_length=300)
    receiveEmail = models.BooleanField(default=True)
    receiveInfo = models.BooleanField(default=True)
    receiveSuccess = models.BooleanField(default=True)
    receiveWarning = models.BooleanField(default=True)
    receiveDanger = models.BooleanField(default=True)
    dateCreated = models.DateTimeField(auto_now=True, auto_now_add=False, default=timezone.now())
    safeDialCode = models.CharField(max_length=4)
    wishlistSpending = models.DecimalField(max_digits=19, decimal_places=2, default=0)

    def getAccounts(self): # method for fetching all the accounts associated with a person
        return Account.objects.filter(owner__pk = self.pk) # filter works, because account has an owner, so the query looks for the primary key of the owner, wich is the owner object's pk

    def __str__(self):		 # tostring method
        return str(self.user.username)

# Validate transfer also simulates a foreign bank
class OutgoingTransaction(models.Model): # This class represents a bank transfer between two parties and is used by the accounts.forms under TransactionForm

    fromUser = models.ForeignKey(User)
    fromAccount = models.ForeignKey('Account')
    toName = models.CharField(max_length=200)
    toSortCode = models.CharField(max_length = 6, validators = [validate_sort])
    toIban = models.CharField(max_length=22, validators = [validate_iban])
    amount = models.FloatField(validators=[validate_transaction_amount])
    balance = models.FloatField(blank=True) # how much money was the balance at this time
    theDate = models.DateTimeField(default=timezone.now)
    description = models.TextField()

    def __str__(self):
        return str(self.amount) + " from " + str(self.fromUser) + " to " + str(self.toName)

class IncomingTransaction(models.Model):
    toUser = models.ForeignKey(User)
    toAccount = models.ForeignKey('Account')
    fromName = models.CharField(max_length=200)
    fromIban = models.CharField(max_length=22)
    amount = models.FloatField(validators=[validate_transaction_amount])
    balance = models.FloatField() # how much money was the balance at this time
    theDate = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=30)

    def __str__(self):
        return 'Received %s from %s' % (self.amount, self.fromName)

class Account(models.Model):

    accountName = models.CharField(max_length = 200)
    accountNumber = models.CharField(max_length=8)
    sortCode = models.IntegerField( validators=[validate_sort], max_length = 6) #[00-00-00]
    iban = models.CharField(max_length = 22, validators=[validate_iban]) #[BG16 RZBB 9155 8520 0224 29]
    amount = models.FloatField()
    overdraft = models.FloatField()
    owner = models.ForeignKey(User)

    def __str__(self): # also known as toString method in java, everywhere where you print an account object will call this method ( admin, shell html/template ).

        accPrint = str(self.iban) # Get the value to print and convert it to string for more flexible manipulation
        newstring = "" 										 # create the empty string that will contain the xxxx-xxxx-xxxx-xxxx separation
        for i in range(0,len(accPrint)): # Iterate over each character in the long digit
            newstring += accPrint[i]
            if (i+1) % 4 == 0: 							 # iterate through the account number string and add a "-" every 4th place, counter<15 is so that the re is no dash at the end
                newstring += '-'
        return str(newstring)

# transfers money from "this" account to a foreign accound
    def transfer(self, **kwargs): # parameters are the name, sort code, account number of the destination and the amount
        api = False # by default a transfer is not an api call
        name=kwargs.get('name')
        iban=kwargs.get('iban')
        sort=kwargs.get('sort')
        amount=kwargs.get('amount')

        api = kwargs.get('api')

        if api is not None:
            api = bool(api)

# debug
        if api:
            print "Transaction is an api call"
# debug

        # validate kwargs here
        if name is None or iban is None or sort is None or amount is None:
            raise ValidationError("The arguments are name, iban, sort and amount. The function also takes optional description argument.")
        if 'description' in kwargs:
            description=kwargs.get('description')
        else:
            description = 'no description'

        # if remoteAccount was not fetched, that will throw an error, otherwise the below code will be executed
        if (self.amount-amount+self.overdraft) < 0:
            raise ValidationError("You don't have enough funds to do the transaction")	# for redundancy, this checks if you can remove money from you

        if validate_transfer(self, name, iban, sort, amount, description):
            bankingP = BankingPerson.objects.get(user = self.owner)

            if not api:
                oTransaction = OutgoingTransaction(fromUser = self.owner, fromAccount = self, toSortCode = sort, toName = name, toIban = iban, amount = amount, description = description, balance = self.amount)
                oTransaction.save()
            # generate a notification under certain circumstances
            if self.amount >= 0 and self.amount < 50:
                if bankingP.receiveWarning:
                    Notification.objects.create(title='Low Balance Alert!', level=2, to=self.owner, text='Warning, your balance is %s' % self.amount)
            elif self.amount<0:
                if bankingP.receiveDanger:
                    Notification.objects.create(title='You are in overdraft!', level=3, to=self.owner, text='Warning, your balance is in overdraft, current amount is %s' % self.amount)
            else:
                pass

            return 0
        else:
            return 1

    def create(self): # Automation script for creating a new account of a certain type
        # from http://stackoverflow.com/questions/2257441/random-string-generation-with-upper-case-letters-and-digits-in-python
        # check if sort or account number is unique
        collision=True # assume collision has occurred, check with the database and then move on

        while(collision): # while there is a collision, generate an account and sort code
            iban = 0
            sortCode = 0
            while(len(str(iban)) != 22): # sometimes a number will be appended by zero, so this is required
                iban = int(random.random() * 10000000000000000000000)
            while(len(str(sortCode)) != 6):
                sortCode = int(random.random() * 1000000)

            try: # check if a collision has been encountered
                Account.objects.get(iban=iban)
                Account.objects.get(sortCode=sortCode)

            except Account.DoesNotExist: # if not, stop the while loop
                collision = False

        # endcheck
        self.iban = iban # set account number of the new account
        self.sortCode = sortCode 		# and the sortcode

        # now the account number is the reminder last 8 digits of the iban
        self.accountNumber = int(str(iban)[-8:])
        self.overdraft = 200 		# set the default overdraft
        self.amount = 200 			# set initial amount
        return self # function returns an account object

def validate_transfer(fromAccount, name, iban, sortCode, amount, description): # this function is used by transfer as the success/fail flag, it will tell it if an entry exists, thus transaction is successful. The function simulates another bank api call.
    if amount <= 0:
        return False
    try:
        bankAccount = Account.objects.get(iban=iban, sortCode=sortCode) # fetch the bank account
        theUser = bankAccount.owner
        bankingP = BankingPerson.objects.get(user=theUser)
    except Account.DoesNotExist:
        bankAccount = None

    if bankAccount is not None: # if account is found

Bank/payment/forms.py
# Code written by Plamen Kolev

from django import forms
from payment.models import BankingPerson, Account, OutgoingTransaction, SavedPayee
from django.utils import timezone
from django.core.exceptions import ValidationError


class OutgoingTransactionForm(forms.ModelForm):

    account = forms.ChoiceField()

    def __init__(self,*args, **kwargs):
        accounts = kwargs.pop('accounts') # the arguments are popped from the view wich looks like this TransactionForm(accounts = accountobject), used to fetch all accounts belonging to a person

        super(OutgoingTransactionForm, self).__init__(*args,**kwargs)

        choices = [] #
        # IF ZERO FIX ERROR !
        for acc in accounts: # generate a tuple of acc options
            choices.append((acc.accountNumber, acc.accountName + ' $' + str(acc.amount)))
        self.fields['account'].choices = choices

    class Meta:
        model = OutgoingTransaction # meta establishes a link between the model of a transaction and this form called Transaction form
        exclude = ('fromObject', 'fromAccount', 'balance', 'theDate') # doesn't render those fields inside the form html
        widgets = {
            'amount' : forms.TextInput(attrs={'placeholder': ''})
    }

class AccountRenameForm(forms.ModelForm):
    class Meta:
        model = Account
        exclude = ('accountName',)

class SavedPayeeForm(forms.ModelForm):
    class Meta:
        model = SavedPayee
        exclude = ("owner",)

Bank/templates/payment/forms/saved_payee_form.html
{% extends 'base.html' %}

{% block 'saved_payee_form' %}
    <div class="col-md-12 white_background">
        <form method="POST" action="{% url 'save_to_payee' %}">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit"/>
        </form>

    </div>
{% endblock %}

Bank/templates/payment/forms/sendMoney_form.html
{% extends 'base.html' %}

{% block 'sendMoney' %}
	{# This is the form responsible for sending money #}
	{# uses the sendMoney url which is in account.urls #}
	<div class="col-md-12 white_background">
	<h1>Transfer money</h1>
	<hr/>
		<div class="col-md-6">
			<p>Someone new</p>
			<div class="form_container">

                <a href="{% url 'save_to_payee' %}">Add to payee list</a>

				<form action="{% url 'sendMoney' %}" method="post" class="col-md-12 payment_form">
					{% csrf_token %} {# a 100% must have token for the django security functions #}
					{# you can also iterate for item in form, but just printing the form displays it properly. It is populated using the account.form classes #}
					{% for error in formError %} {# the error message are set from within the view in accounts #}
						<div class="alert alert-danger">
							<p>{{error}}</p>
						</div>
					{% endfor %}

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Name:</span>
						<div class="col-md-8">{{form.toName}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Account IBAN:</span>
						<div class="col-md-8">{{form.toIban}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Sort-Code:</span>
						<div class="col-md-8">{{form.toSortCode}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">From account:</span>
						<div class="col-md-8">{{form.account}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Description:</span>
						<div class="col-md-8">{{form.description}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Amount:</span>
						<div class="col-md-8">{{form.amount}}</div>
					</div>

					<div class="col-md-12 payment_fields_div_container">



					</div>

					<div class="col-md-12 payment_fields_div_container">
						<span class="col-md-4">Pay:</span><div class="col-md-2"><input class="jquery_pressed_handler_hide" type="radio" checked=checked name="pay_when" value='now' /></div>

						<div class="col-md-4 pull-right">
							<input style="color:white" class="col-md-6 transaction_submit_button jquery_pressed_handler_show" type="submit" value="Transfer" />
						</div>

					</div>

				</form>

				</div>
		</div>
		<div class="col-md-6">
			<p>Payee list</p>
			<div class="payee_list_container">
				<ul>

					{% for payee in payeeList %}
					<script>
					var name = ".{{payee.name}}";
					
					$(document).on('click', name, function(name){ 
					     var payeename = $(this).children(".payee_name").text();
					     var payeeiban = $(this).children(".payee_iban").text();
					     var payeesort = $(this).children(".payee_sort").text();

					     $("#id_toName").val(payeename);
					     $("#id_toIban").val(payeeiban);
					     $("#id_toSortCode").val(payeesort);
					 });

					</script>
						<div class="{{payee.name}}">
							<p class="payee_name">{{payee.name}}</p>
							<p class="payee_iban">{{payee.iban}}</p>
							<p class="payee_sort">{{payee.sortCode}}</p>
							<hr/>
						</div>

					{% endfor %}
				</ul>
			</div>


		</div>

	</div>

<script charset="utf-8">
	$(document).ready(function(){


    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

		$(".save_to_payee_list").click(function(){

			function add_new_payee_validator(){
				return true;
			}

			if(add_new_payee_validator()){
				console.log($("#id_toName").val());
				console.log($("#id_toIban").val());
				console.log($("#id_toSortCode").val());
            }

            $.ajax({
                url: "{% url 'savedpay' %}",
                dataType: 'json',
                type: "POST",
                headers: {
                    "Authorization": "token b256e4e9309879cf7eeff0d22843eede85b0ac52"
                },

                "csrfmiddlewaretoken": csrftoken,

                success: function (data){
                    alert('Thanks for your comment! ' + data);
                }
            });

         });


    });

</script>

{% endblock %}